### PR TITLE
Fix AttributeError: 'int' object has no attribute 'decode'

### PR DESCRIPTION
**Pull request by wiktorn**
When using pyosmium-get-changes, which use urllib to download changes from
remote server it was failing due to the fact, that call to
urllib.response.readline() was returning bytes, which were in the for loop
interpeted one by one.

### CODE REVIEW

**Comment by lonvia** [comment]
The Python 3.5 problem was actually a problem of building against pybind11 master, which is not the best idea. I've fixed the CI runs on master. And hopefully I've stop Appveyor from doing stuff, too. Can you rebase and remove the CI changes?

**Comment by wiktorn** [comment]
Removed the commit and rebased.

**Comment by lonvia** [comment]
While investigating the memory leak and writing tests, I realized that this can be done in an even simpler way, see https://github.com/osmcode/pyosmium/blob/7ab5ec6abbd79d6d8171f4872c06d32545ec5ec2/src/osmium/replication/server.py#L328-L334 Could you quickly check if master still works for you? If not we really need a test to reproduce the issue.

**Comment by wiktorn** [comment]
Ok, confirmed that it still works. Thanks, and indeed it's a ton simpler.

**Pull request merged**
