### PR TITLE
Appveyor support

### PR DESCRIPTION
**Pull request by lonvia**
This is #35 with some cleanup of setup.py. Visual C++ has a nifty auto-linking feature which means we don't need to care about the exact name of the boost library. Makes the code quite a bit more simple.

I've also tried to add python 2.7 to the matrix but that fails because half the include paths are missing. @alex85k you said that you had that working already. Is there any special treatment required?

### CODE REVIEW

**Comment by alex85k** [comment]
Currently Python 2.7 tries to use extremely old Visual Studio. It can be switched to VS2015 by adding
```
SET VS90COMNTOOLS=%VS140COMNTOOLS%
```
to the build script. It will also need different boost_python lib+dll but it happens to be inside the development pack already.

**Comment by alex85k** [comment]
Hmm, VS90COMNTOOLS not working... Testing more

**Comment by alex85k** [comment]
Solved the puzzle with outdated VS  used for Python2.7. We have to make old compilers unusable so setuotools will not find it:
```
  - SET VS90COMNTOOLS=%VS140COMNTOOLS%
  - SET VS100COMNTOOLS=%VS140COMNTOOLS%
  - SET VS110COMNTOOLS=%VS140COMNTOOLS%
  - SET VS120COMNTOOLS=%VS140COMNTOOLS%
  - cd "c:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\"
  - ren "Visual C++ for Python" "Visual C++ for Python Do Not Use"
  - cd "C:\Program Files (x86)\"
  - ren "Microsoft Visual Studio 9.0" "Microsoft Visual Studio 9.0 Do Not Use"
```
However, the boost-auto linking seems to not work this time:
https://ci.appveyor.com/project/alex85k/pyosmium/build/1.0.25
(or .lib is incorrectly generated)

**Comment by lonvia** [comment]
It's actually the old compiler I want. python libraries must be built with the same compiler as the python interpreter and for 2.7 that happens to be this ancient VC9. I would expect that the boost-python libraries are built with that compiler as well.

**Comment by lonvia** [comment]
Or maybe not. boost-python itself looks like they are building against VC14. I'm confused.

I'll commit the python3 part for now, so that there is something to start with.

**Pull request merged**
